spring.application.name=producer
spring.datasource.url=jdbc:h2:mem:rabbitMQdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=test
spring.datasource.password=test
spring.jpa.database.platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

queue=employee-queue
exchange=employee-exchange
routingKey=test


server.port=8080